### ISSUE TITLE
ToDo:  Add a stupid game loop

### ISSUE THREAD

**Issue by Sillinde** [Sillinde/Sillinde.github.io#1]
Add a stupid game loop.  It's a whole two lines of code.  And everything that happens "per tick" gets called between those two lines of code.  Why haven't I done this already?  I'm lazy.  lol

**Comment by TheAntonverse** [comment]
I did add one in my time tinkering tonight, borrowed from that incremental games jsfiddle you showed me.

**Comment by Sillinde** [comment]
Looked through the files you sent.  Didn't see an interval loop in there.  Added it.  It's on the test branch, now.  Unless I missed it, and we now have two loops.  XD
